### ISSUE TITLE
UsingJavaInJavaScriptAdapters ConfigurationAPI issue

### ISSUE THREAD

**Issue by gianlucainnocente** [MobileFirst-Platform-Developer-Center/Adapters#1]
Hi,

in our MobileFirst project, we are using Javascript adapters, but we have many utilities in Java code.
These utilities need to read MobileFirst properties using ConfigurationAPI. The problem is that configurationApi variable is always null.

Here is my example code:
`public class ResponseUtils {

	@Context 
	public ConfigurationAPI configurationAPI ;

         public static Scriptable createGenericResponse(String statusKey) {
		System.out.println("Test config:"+ResponseUtils.configurationAPI);
		
		return createGenericResponse(statusKey, null);
	}
}`

I'm calling the "createGenericResponse" method from javascript adapters.

Where is the problem?

Thank you

**Comment by IdanAdar** [comment]
Hi, this question should be posted to stackoverflow and I see that it is there. Let's continue there: http://stackoverflow.com/q/41239859/1530814
